version: '3.8'

services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - ./data:/workspace/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''

  mlflow:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace
      - ./mlruns:/workspace/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000

volumes:
  mlruns: